[[redirects]]
  from = "https://behshad-appointment-planners.netlify.app/contacts/*"
  to = "https://behshad-appointment-planners.netlify.app/"
  status = 301
  force = true
[[redirects]]
  from = "https://behshad-appointment-planners.netlify.app/appointments/*"
  to = "https://behshad-appointment-planners.netlify.app/"
  status = 301
  force = true